group: travis_latest
language: python
cache: pip
python: 3.8
install: pip install flake8  # pytest
before_script: flake8 . --count --max-complexity=10 --max-line-length=88 --show-source --statistics
script: true  # pytest --capture=sys  # add other tests here
